#!/bin/bash

# Copyright (C) 2010 Oregon State University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e
. ./common.sh
debug set -x

# If the target device is not a real block device we'll first losetup it.
# This is needed for file disks.
if ! test -b "$BLOCKDEV"; then
    OLD_BLOCKDEV="$BLOCKDEV"
    BLOCKDEV="$("$LOSETUP" -sf "$BLOCKDEV")"
    CLEANUP+=("\"$LOSETUP\" -d \"$BLOCKDEV\"")
fi

if ! test 'yes' = "$NOMOUNT"; then
    filesystem_dev="$(map_disk0)"
    CLEANUP+=('unmap_disk0')
    root_dev="$(map_partition "$filesystem_dev" root)"
    boot_dev="$(map_partition "$filesystem_dev" boot)"
fi

TARGET="`mktemp -d --tmpdir="${EXPORT_DIR:-${TMPDIR:-/tmp}}"`"
CLEANUP+=("rmdir \"$TARGET\"")

if test 'yes' = "$NOMOUNT"; then
    # convert block device to qcow2 image to support OS's like Windows. Use
    # qcow2 to conserve on space.
    "$QEMU_IMG" convert "$BLOCKDEV" -O qcow2 "${TARGET}/disk.img"
    CLEANUP+=("rm -f \"${TARGET}/disk.img\"")
else
    vol_type_root="$(eval "$VOL_TYPE \"$root_dev\"")"
    test -z "$boot_dev" || vol_type_boot="$(eval "$VOL_TYPE \"$boot_dev\"")"

    for _fs in 'boot' 'root'; do
        # use indirect reference to make the variables dynamic (these are a mess, fix in an
        # upcoming commit)
        dev="$(eval "echo \${$(echo ${_fs}_dev)"})"
        vol_type="$(eval echo \$vol_type_${_fs})"
        test -n "$vol_type" || test -z "$dev" || { log_error "Unable to find $_fs filesystem type at $dev"; exit 1; }
        if test -n "$dev"; then
            case "$vol_type" in
                ext3|ext2|ext4)
                    "$DUMP" -0 -q -z9 -f "${TARGET}/${_fs}.dump" "$dev"
                    CLEANUP+=("rm -f \"${TARGET}/${_fs}.dump\"")
                    ;;
                *)
                    log_error "$_fs is not a supported filesystem. Please use ext{2,3,4}"
                    exit 1
                    ;;
            esac
        fi
    done
fi

( cd "$TARGET"; tar -cf - . )

# execute cleanups
cleanup
trap - EXIT
