#!/bin/sh

# Copyright (C) 2010, 2011, 2012 Oregon State University
# Copyright (C) 2013, 2014, 2015 GRNET S.A.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e
. ./common.sh
debug set -x

# TODO:
# * use $EXPORT_INDEX

losetup_blockdev
test -z "$EXP_SIZE_FD" || "$BLOCKDEV_CMD" --getsize64 "$BLOCKDEV" >&$EXP_SIZE_FD
mkdir_disk0_temp
if test 'yes' = "$NOMOUNT"; then
    "$QEMU_IMG" convert "$BLOCKDEV" -O 'qcow2' -c "${TARGET}/disk.img"
    cleanup push "rm -f \"${TARGET}/disk.img\""
else
    map_all
    vol_type_root="$(eval "$VOL_TYPE \"${root_dev:-$ROOT_DEV}\"")"
    test -z "$boot_dev" || vol_type_boot="$(eval "$VOL_TYPE \"${boot_dev:-$BOOT_DEV}\"")"
    for _fs in 'boot' 'root'; do
        eval "_dev=\"\$${_fs}_dev\""
        eval "_vol_type=\"\$vol_type_$_fs\""
        if test -n "$_dev"; then
            case "$_vol_type" in
                ext2|ext3|ext4)
                    "$DUMP" -0 -q -z9 -f "${TARGET}/${_fs}.dump" "$_dev"
                    cleanup push "rm -f \"${TARGET}/${_fs}.dump\""
                    ;;
                '')
                    die 'Unable to find filesystem type at "%s"\n' "$_dev"
                    ;;
                *)
                    die '%s is not a supported filesystem. Please use ext{2,3,4}\n' "$_fs"
                    ;;
            esac
        fi
    done
fi
( cd "$TARGET" && tar -cf - . )
