#!/bin/bash

# Copyright (C) 2010, 2011, 2012 Oregon State University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e
. ./common.sh
debug set -x

losetup_blockdev
mkdir_disk0_temp 'dump'
if ! test 'yes' = "$NOMOUNT"; then
    format_disk0 "$BLOCKDEV"
    map_all
    mkfs_disk0
    get_uuids
    mount_disk0
fi
# import dumps from tar file
( cd "$DUMPDIR" && tar -xf - )
if test 'yes' = "$NOMOUNT"; then
    "$QEMU_IMG" convert "${DUMPDIR}/disk.img" -O 'host_device' "$BLOCKDEV"
else
    # clean up any previous restore runs
    rm -rf /tmp/rst*
    ( cd "$TARGET" && restore -r -y -f "${DUMPDIR}/root.dump" )
    test -z "$boot_dev" || ( cd "${TARGET}/boot" && restore -r -y -f "${DUMPDIR}/boot.dump" )
    setup_fstab
    ! test 'True' = "$INSTANCE_HV_serial_console" || setup_console
    rm -f "${TARGET}/etc/udev/rules.d/z"*"_persistent-net.rules"
    if test -x "${CUSTOMIZE_DIR}/grub"; then
        ROOT_DEV="$root_dev"; BOOT_DEV="$boot_dev"; IMPORT_SCRIPT=1
        export TARGET SUITE BLOCKDEV ROOT_DEV BOOT_DEV IMG_SSH_KEY_URL IMPORT_SCRIPT
        # Install grub as we're not deploying via qcow
        "${CUSTOMIZE_DIR}/grub"
    fi
fi
