#!/bin/bash

# Copyright (C) 2010, 2011, 2012 Oregon State University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e
. ./common.sh
debug set -x

! test 'yes' = "$NOMOUNT" || exit 0
losetup_blockdev
map_all
TARGET="`mktemp -d`"
cleanup push "rmdir \"$TARGET\""
mount_disk0
get_os_type
case "$OS_TYPE" in
    debian)
        HNAME="${TARGET}/etc/hostname"
        OLD_HNAME="$(cat "$HNAME")"
        ;;
    redhat)
        HNAME="${TARGET}/etc/sysconfig/network"
        OLD_HNAME="$(
            grep 'HOSTNAME' "$HNAME" | \
                sed -e 's/HOSTNAME=//' | \
                sed -e 's/"//g'
        )"
        ;;
    gentoo)
        HNAME="${TARGET}/etc/conf.d/hostname"
        # baselayout-2.x support
        if test -d "${TARGET}/usr/share/openrc"; then
            OLD_HNAME="$(
                grep 'hostname' "$HNAME" | \
                    sed -e 's/hostname=//' | \
                    sed -e 's/"//g'
            )"
        else
            OLD_HNAME="$(
                grep 'HOSTNAME' "$HNAME" | \
                    sed -e 's/HOSTNAME=//' | \
                    sed -e 's/"//g'
            )"
        fi
        ;;
    suse)
        HNAME="${TARGET}/etc/HOSTNAME"
        OLD_HNAME="$(cat "$HNAME")"
        ;;
esac
if test "x$OLD_HNAME" = "x$old_name" || \
    test "x${OLD_HNAME}.`printf '%s' "$old_name" | cut -d. -f2,3`" = "x$old_name"; then
    case "$OS_TYPE" in
        debian|suse)
            printf '%s\n' "$instance" >"$HNAME"
            ;;
        redhat)
            sed --follow-symlinks -i -e 's/HOSTNAME='"$OLD_HNAME"'/HOSTNAME='"$instance"'/' "$HNAME"
            ;;
        gentoo)
            if test -d "${TARGET}/usr/share/openrc"; then
                sed --follow-symlinks -i -e 's/hostname.*/hostname="'"$instance"'"/' "$HNAME"
            else
                sed --follow-symlinks -i -e 's/HOSTNAME.*/HOSTNAME="'"$instance"'"/' "$HNAME"
            fi
            ;;
    esac
    if test -x "${CUSTOMIZE_DIR}/zz_ddns"; then
        TARGET="$TARGET"
        export TARGET
        "${CUSTOMIZE_DIR}/zz_ddns" -r
    fi
else
    die 'Cannot rename from %s to %s:\nInstance has a different hostname (%s)\n' "$old_name" "$instance" "$OLD_HNAME"
fi
