#!/bin/sh

# Copyright (C) 2010, 2011, 2012 Oregon State University
# Copyright (C) 2013, 2014, 2015 GRNET S.A.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

exit 0

## The preexisting and expected behaviour is to do the below so that the VM's
## sense of its hostname stays in sync across renames, but we (grnet NOC) deal
## with this separately, and therefore need the provider to be a noop here, so
## have commented this out. Most other users will want to uncomment this
## though...

#set -e
#. ./common.sh
#debug set -x
#
#! test 'yes' = "$NOMOUNT" || exit 0
#losetup_blockdev
#map_all
#mkdir_disk0_temp
#mount_disk0
#get_os_type
#change_hostname
