#!/bin/bash

case "$OSP_IMG_FORMAT" in
    tarball|qemu|dump)
        :
        ;;
    *)
        printf 'Wrong image format. Supported formats are: qemu, tarball, dump.\n' >&2
        exit 1
        ;;
esac
