#!/bin/sh

# Copyright (C) 2010, 2011, 2012 Oregon State University
# Copyright (C) 2013, 2014, 2015 GRNET S.A.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

check_api10_parameters() {
    test -n "$INSTANCE_NAME" && test -n "$HYPERVISOR" && test -n "$DISK_COUNT" || \
        die 'Missing OS API Variable:\n(INSTANCE_NAME, HYPERVISOR or DISK_COUNT)\n'
    test 1 -le $DISK_COUNT && test -n "$DISK_0_PATH" || die 'At least one disk is needed\n'
    case "$SCRIPT_NAME" in
        export)
            test -n "$EXPORT_DEVICE" || die 'Missing OS API Variable EXPORT_DEVICE\n'
            ;;
        import)
            test -n "$IMPORT_DEVICE" || die 'Missing OS API Variable IMPORT_DEVICE\n'
            ;;
    esac
    ! test 'rename' = "$SCRIPT_NAME" || test -n "$OLD_INSTANCE_NAME" || \
        die 'Missing OS API Variable OLD_INSTANCE_NAME\n'
}

check_api20_parameters() {
    case "$OSP_IMG_FORMAT" in
        tarball|qemu|dump)
            :
            ;;
        *)
            die 'Wrong image format "%s" for OSP_IMG_FORMAT. Supported formats are: qemu, tarball, dump.\n' "$OSP_IMG_FORMAT"
            ;;
    esac
    test -n "$OSP_IMG_ID" || die 'Missing OS image ID (OSP_IMG_ID),\n'
    # $OSP_IMG_PASSWD is optional...
    case "$OSP_IMG_NOMOUNT" in
        yes|no|'')
            :
            ;;
        *)
            die 'Invalid argument "%s" for OSP_IMG_NOMOUNT. Must be "yes" or "no".\n' "$OSP_IMG_NOMOUNT"
            ;;
    esac
}

case "$OS_API_VERSION" in
    4|5|10|15)
        die 'Obsolete OS API VERSION "%s"\n' "$OS_API_VERSION"
        ;;
    20)
        check_api10_parameters
        check_api20_parameters
        ;;
    *)
        die 'Unknown OS API VERSION "%s"\n' "$OS_API_VERSION"
        ;;
esac
