#!/bin/sh

# Copyright (C) 2006, 2007 Google Inc.
# Copyright (C) 2010, 2011, 2012 Oregon State University
# Copyright (C) 2013, 2014, 2015 GRNET S.A.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

# This is a test script to ease development and testing on test clusters.
# It should not be used to update production environments.

# Usage: upload node-{1,2,3}

set -e

hosts=''
while test $# -gt 0; do
    _opt="$1"
    case "$_opt" in
        -h|--help)
            printf 'Usage: %s hosts...\n' "$0"
            exit 0
            ;;
        -*)
            printf 'Unknown option: %s\n' "$_opt" >&2
            exit 1
            ;;
        *)
            hosts="$hosts $_opt"
            ;;
    esac
    shift
done

set -- $hosts
TXD="`mktemp -d`"
trap 'rm -rf "$TXD"' EXIT
make install DESTDIR="$TXD"
printf '---\n'
( cd "$TXD" && find )
printf '---\n'
for _host; do
    printf 'Uploading code to %s...\n' "$_host"
    rsync -v -rlDc "$TXD"/* "root@${_host}:/" &
done
wait
