#!/bin/bash

#
# Copyright (C) 2011 Greek Research and Technology Network
#

set -e
. ./common.sh
debug set -x

n="`od -An -N1 -t u1 '/dev/urandom'`"
min=`expr $n % 30 || :`

cat >"${TARGET}/etc/crontab" <<EOF
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m h dom mon dow user  command
$min * * * *      root    cd / && run-parts --report cron.hourly
`expr $min + 7` 6 * * *  root    test -x /usr/sbin/anacron || ( cd / && run-parts --report cron.daily )
`expr $min + 13` 6 * * 7 root    test -x /usr/sbin/anacron || ( cd / && run-parts --report cron.weekly )
`expr $min + 24` 6 1 * * root    test -x /usr/sbin/anacron || ( cd / && run-parts --report cron.monthly )
EOF
