#!/bin/bash

#
# Copyright (C) 2011 Greek Research and Technology Network
#

set -e

. common.sh

debug set -x

if [ -n "${IMG_SSH_KEY_URL}" ]; then
       ${MKDIR_P} ${TARGET}/root/.ssh
       wget -q -O "${TARGET}/root/.ssh/authorized_keys" "${IMG_SSH_KEY_URL}"
       echo "Succesfully injected ssh key"
fi

cleanup
trap - EXIT
exit 0

