#!/bin/sh

# Copyright (C) 2014, 2015 GRNET S.A.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#
# This is an example script that injects a root SSH key.

set -e
. ./common.sh
debug set -x

if test -n "$IMG_SSH_KEY_URL"; then
    $MKDIR_P "${TARGET}/root/.ssh"
    $WGET -q -O- "$IMG_SSH_KEY_URL" >"${TARGET}/root/.ssh/authorized_keys" 2>/dev/null
    verbprint 'Succesfully injected ssh key\n'
fi
