#!/bin/sh

#
# Copyright (C) 2011 Greek Research and Technology Network
#

set -e
. ./common.sh
debug set -x

if test -n "$IMG_SSH_KEY_URL"; then
    $MKDIR_P "${TARGET}/root/.ssh"
    $WGET -q -O- "$IMG_SSH_KEY_URL" >"${TARGET}/root/.ssh/authorized_keys" 2>/dev/null
    verbprint 'Succesfully injected ssh key\n'
fi
