#!/bin/sh

# Copyright (C) 2010 Oregon State University
# Copyright (C) 2013, 2014, 2015 GRNET S.A.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#
# Remove all generated keys so that each instance has unique keys for ssh

set -e
. ./common.sh
debug set -x

HOST_KEY='/etc/ssh/ssh_host_key'
RSA_KEY='/etc/ssh/ssh_host_rsa_key'
DSA_KEY='/etc/ssh/ssh_host_dsa_key'
ECDSA_KEY='/etc/ssh/ssh_host_ecdsa_key'
ED25519_KEY='/etc/ssh/ssh_host_ed25519_key'
if test -e "${TARGET}/etc/debian_version"; then
    printerr 'Debian/Ubuntu: replace existing ssh keys\n'
    rm -f "${TARGET}/$HOST_KEY" 2>/dev/null || :
    if ls "${TARGET}/$RSA_KEY"* >/dev/null 2>&1; then
        rm -f "${TARGET}/$RSA_KEY"*
        ssh-keygen -t 'rsa' -q -N '' -f "${TARGET}/$RSA_KEY"
    fi
    if ls "${TARGET}/$DSA_KEY"* >/dev/null 2>&1; then
        rm -f "${TARGET}/$DSA_KEY"*
        ssh-keygen -t 'dsa' -q -N '' -f "${TARGET}/$DSA_KEY"
    fi
    if ls "${TARGET}/$ECDSA_KEY"* >/dev/null 2>&1; then
        rm -f "${TARGET}/$ECDSA_KEY"*
        ssh-keygen -t 'ecdsa' -q -N '' -f "${TARGET}/$ECDSA_KEY"
    fi
    if ls "${TARGET}/$ED25519_KEY"* >/dev/null 2>&1; then
        rm -f "${TARGET}/$ED25519_KEY"*
        ssh-keygen -t 'ed25519' -q -N '' -f "${TARGET}/$ED25519_KEY"
    fi
else
    for _key in "$HOST_KEY" "$RSA_KEY" "$DSA_KEY" "$ECDSA_KEY" "$ED25519_KEY"; do
        ! ls "${TARGET}/$_key"* >/dev/null 2>&1 || rm -f "${TARGET}/$_key"*
    done
fi
