#!/bin/bash

# Copyright (C) 2010 Oregon State University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#
# Remove all generated keys so that each instance has unique keys for ssh

set -e
. ./common.sh
debug set -x

HOST_KEY='/etc/ssh/ssh_host_key'
RSA_KEY='/etc/ssh/ssh_host_rsa_key'
DSA_KEY='/etc/ssh/ssh_host_dsa_key'
if test -e "${TARGET}/etc/debian_version"; then
    verbprint 'Debian/Ubuntu: replace existing ssh keys\n'
    rm -f "${TARGET}/$HOST_KEY" 2>/dev/null || :
    if rm -f "${TARGET}/$RSA_KEY"* 2>/dev/null; then
        ssh-keygen -t 'rsa' -q -N '' -f "${TARGET}/$RSA_KEY"
    fi
    if rm -f "${TARGET}/$DSA_KEY"* 2>/dev/null; then
        ssh-keygen -t 'dsa' -q -N '' -f "${TARGET}/$DSA_KEY"
    fi
else
    for _key in "$HOST_KEY" "$RSA_KEY" "$DSA_KEY"; do
        rm -f "${TARGET}/$_key"* 2>/dev/null || :
    done
fi
