#!/bin/sh

# Copyright (C) 2011, 2012 Oregon State University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#
# This is an example script that configures your DHCP clients to set "send
# host-name" so that Dynamic DNS work properly after installation.

set -e
. ./common.sh
debug set -x

FQDN="$INSTANCE_NAME"
SHORT_NAME="$(printf '%s' "$INSTANCE_NAME" | cut -d. -f1)"
RENAME=''
test -d "$TARGET" || die 'Missing target directory\n'
while getopts 'r' _opt; do
    ! test 'r' = "$_opt" || RENAME='true'
done

_debian_setup() {
    _dhclient_conf=''
    if test -f "${TARGET}/etc/dhcp/dhclient.conf"; then
        _dhclient_conf="${TARGET}/etc/dhcp/dhclient.conf"
    elif test -f "${TARGET}/etc/dhcp3/dhclient.conf"; then
        _dhclient_conf="${TARGET}/etc/dhcp3/dhclient.conf"
    else
        die 'Missing dhclient.conf file\n'
    fi
    if test -n "$FQDN" && test -z "$RENAME"; then
        printf 'send host-name %s;' "$SHORT_NAME" >>"$_dhclient_conf"
    else
        sed --follow-symlinks -i -e 's/send host-name.*/send host-name '"$SHORT_NAME"';/' "$_dhclient_conf"
    fi
}

_redhat_setup() {
    test -f "${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0" || die 'Missing ifcfg-eth0 file\n'
    if test -n "$FQDN" && test -z "$RENAME"; then
        printf 'DHCP_HOSTNAME=%s' "$SHORT_NAME" >>"${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0"
    else
        sed --follow-symlinks -i -e 's/DHCP_HOSTNAME=.*/DHCP_HOSTNAME='"$SHORT_NAME"'/' "${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0"
    fi
}

_gentoo_setup() { verbprint 'no action needed for ddns\n'; }

_suse_setup() { verbprint 'untested for suse\n'; }

get_os_type
if test 0 -lt $NIC_COUNT; then
    die 'No nics defined\n'
elif test -z "$OS_TYPE"; then
    die 'Unsupported OS_TYPE\n'
else
    "_${OS_TYPE}_setup"
fi
